
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rola
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */private boolean flaguser = false;
      private boolean flagPass = false;
      private boolean flag = false;

     
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PhoneNum = new javax.swing.JTextField();
        Button = new javax.swing.JButton();
        jLabelRegester = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("Register");

        jLabelClose.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone number:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");

        PhoneNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumActionPerformed(evt);
            }
        });
        PhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneNumKeyPressed(evt);
            }
        });

        Button.setBackground(new java.awt.Color(102, 153, 255));
        Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button.setText("Register");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jLabelRegester.setForeground(new java.awt.Color(102, 204, 255));
        jLabelRegester.setText("Click here to login");
        jLabelRegester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegesterMouseClicked(evt);
            }
        });

        Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameKeyPressed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fullname:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username:");

        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 46, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegester, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addComponent(Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegester, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumActionPerformed

    }//GEN-LAST:event_PhoneNumActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        String name = Name.getText();//get the full name from the JTextField
        String phonenum = PhoneNum.getText();//get the Phone number from the JTextField
        String username = Username.getText();//get the username from the JTextField
        String pass = Password.getText();//get the password from the JTextField
        /*check if  the field is  empty or not
       and the flag = true he/she gets an JOptionPane message error and reset the wendow
       */
         if(username.isEmpty() || pass.isEmpty()|| name.isEmpty()||phonenum.isEmpty()){
             JOptionPane.showMessageDialog(null, "Name/Phone number/"+"Username/Password "+
                     "should not be empty","Error",JOptionPane.ERROR_MESSAGE);
             flag = true;
              Register rgf = new Register();
              rgf.setVisible(true);
              rgf.pack();
              rgf.setLocationRelativeTo(null);
              rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
              this.dispose();
        }else {
             /*if the fields are not empty 
             check if the username and the password are exist or not
             */
             if(flag == false){
                 try{
                     File file = new File("costumers.text");
                     if(!(file.exists())){
                         file.createNewFile();
                     }
                     Scanner scan = new Scanner(file);
                     while(scan.hasNext()){
                         String  line = scan.nextLine();  
                         if (line.equals(username)){
                             flaguser = true;            
                         }
                         if (line.equals(pass)){
                            flagPass = true;            
                         }
                    }
                     
                /* if the username is exist 
                show JOptionPane message error and swich to the login window
                */
                 if(flaguser ){
                        JOptionPane.showMessageDialog(null,"The username is already exist");
                    }
                 /* if the password is exist 
                show JOptionPane message error and swich to the login window
                */
                 if(flagPass){
                        JOptionPane.showMessageDialog(null,"The password is already exist");
                    }
                 /*if the username and the password are not exist
                 complete the regestration and go to the login wendow
                 */
                    if(!(flaguser && flagPass)){
                        try {
                            FileWriter F = new FileWriter("costumers.text",true);
                            PrintWriter Write = new PrintWriter(F);
                            Write.println(name +"\n"+ phonenum +"\n"+ username+"\n" + pass );
                            Write.println("----------------------------------------------------");
                            Write.flush();
                            Write.close();
                            loginForm lgf = new loginForm();
                            lgf.setVisible(true);
                            lgf.pack();
                            lgf.setLocationRelativeTo(null);
                            lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
          
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                    
                    }
                
            }catch(Exception e){
                 
            }
       }
         }
    }//GEN-LAST:event_ButtonActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed

    }//GEN-LAST:event_UsernameActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed

    }//GEN-LAST:event_NameActionPerformed

    private void jLabelRegesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegesterMouseClicked
        loginForm lgf = new loginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegesterMouseClicked

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed

    }//GEN-LAST:event_PasswordActionPerformed
/*this method PasswordKeyPressed() allow the user to complete the opration
    by pree the key enter on the keybord
    */
    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
              String name = Name.getText();//get the full name from the JTextField
              String phonenum = PhoneNum.getText();//get the Phone number from the JTextField
              String username = Username.getText();//get the username from the JTextField
              String pass = Password.getText();//get the password from the JTextField
             /*check if  the field is  empty or not
              and the flag = true he/she gets an JOptionPane message error and reset the wendow
               */
         if(username.isEmpty() || pass.isEmpty()|| name.isEmpty()||phonenum.isEmpty()){
             JOptionPane.showMessageDialog(null, "Name/Phone number/"+"Username/Password "+
                     "should not be empty","Error",JOptionPane.ERROR_MESSAGE);
             flag = true;
              Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
        }else {
             /*if the fields are not empty 
             check if the username and the password are exist or not
             */
             if(flag == false){
        try{
                File file = new File("costumers.text");
                Scanner scan = new Scanner(file);
                while(scan.hasNext()){
                    String  line = scan.nextLine();  
                    if (line.equals(username)){
                            flaguser = true;            
                }
                      if (line.equals(pass)){
                            flagPass = true;            
                }
                    }
                /* if the username is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flaguser){
                        JOptionPane.showMessageDialog(null,"The username is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /* if the password is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flagPass){
                        JOptionPane.showMessageDialog(null,"The password is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /*if the username and the password are not exist
                 complete the regestration and go to the login wendow
                 */
                    if(!(flaguser && flagPass)){
                        try {
                            FileWriter F = new FileWriter("costumers.text",true);
                            PrintWriter Write = new PrintWriter(F);
                            Write.println(name +"\n"+ phonenum +"\n"+ username+"\n" + pass );
                            Write.println("----------------------------------------------------");
                            Write.flush();
                            Write.close();
                            loginForm lgf = new loginForm();
                            lgf.setVisible(true);
                            lgf.pack();
                            lgf.setLocationRelativeTo(null);
                            lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
          
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                    
                    }
                
            }catch(Exception e){
                 
            }
       }
         }
        }
    }//GEN-LAST:event_PasswordKeyPressed
/*this method NameKeyPressed() allow the user to complete the opration
    by pree the key enter on the keybord
    */
    private void NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
              String name = Name.getText();//get the full name from the JTextField
        String phonenum = PhoneNum.getText();//get the Phone number from the JTextField
        String username = Username.getText();//get the username from the JTextField
        String pass = Password.getText();//get the password from the JTextField
        /*check if  the field is  empty or not
       and the flag = true he/she gets an JOptionPane message error and reset the wendow
       */
         if(username.isEmpty() || pass.isEmpty()|| name.isEmpty()||phonenum.isEmpty()){
             JOptionPane.showMessageDialog(null, "Name/Phone number/"+"Username/Password "+
                     "should not be empty","Error",JOptionPane.ERROR_MESSAGE);
             flag = true;
              Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
        }else {
             /*if the fields are not empty 
             check if the username and the password are exist or not
             */
             if(flag == false){
        try{
                File file = new File("costumers.text");
                Scanner scan = new Scanner(file);
                while(scan.hasNext()){
                    String  line = scan.nextLine();  
                    if (line.equals(username)){
                            flaguser = true;            
                }
                      if (line.equals(pass)){
                            flagPass = true;            
                }
                    }
                /* if the username is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flaguser){
                        JOptionPane.showMessageDialog(null,"The username is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /* if the password is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flagPass){
                        JOptionPane.showMessageDialog(null,"The password is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /*if the username and the password are not exist
                 complete the regestration and go to the login wendow
                 */
                    if(!(flaguser && flagPass)){
                        try {
                            FileWriter F = new FileWriter("costumers.text",true);
                            PrintWriter Write = new PrintWriter(F);
                            Write.println(name +"\n"+ phonenum +"\n"+ username+"\n" + pass );
                            Write.println("----------------------------------------------------");
                            Write.flush();
                            Write.close();
                            loginForm lgf = new loginForm();
                            lgf.setVisible(true);
                            lgf.pack();
                            lgf.setLocationRelativeTo(null);
                            lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
          
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                    
                    }
                
            }catch(Exception e){
                 
            }
       }
         }
        }                       
    }//GEN-LAST:event_NameKeyPressed
/*this method PhoneNumKeyPressed() allow the user to complete the opration
    by pree the key enter on the keybord
    */
    private void PhoneNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String name = Name.getText();//get the full name from the JTextField
        String phonenum = PhoneNum.getText();//get the Phone number from the JTextField
        String username = Username.getText();//get the username from the JTextField
        String pass = Password.getText();//get the password from the JTextField
        /*check if  the field is  empty or not
       and the flag = true he/she gets an JOptionPane message error and reset the wendow
       */
         if(username.isEmpty() || pass.isEmpty()|| name.isEmpty()||phonenum.isEmpty()){
             JOptionPane.showMessageDialog(null, "Name/Phone number/"+"Username/Password "+
                     "should not be empty","Error",JOptionPane.ERROR_MESSAGE);
             flag = true;
              Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
        }else {
             /*if the fields are not empty 
             check if the username and the password are exist or not
             */
             if(flag == false){
        try{
                File file = new File("costumers.text");
                Scanner scan = new Scanner(file);
                while(scan.hasNext()){
                    String  line = scan.nextLine();  
                    if (line.equals(username)){
                            flaguser = true;            
                }
                      if (line.equals(pass)){
                            flagPass = true;            
                }
                    }
                /* if the username is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flaguser){
                        JOptionPane.showMessageDialog(null,"The username is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /* if the password is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flagPass){
                        JOptionPane.showMessageDialog(null,"The password is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /*if the username and the password are not exist
                 complete the regestration and go to the login wendow
                 */
                    if(!(flaguser && flagPass)){
                        try {
                            FileWriter F = new FileWriter("costumers.text",true);
                            PrintWriter Write = new PrintWriter(F);
                            Write.println(name +"\n"+ phonenum +"\n"+ username+"\n" + pass );
                            Write.println("----------------------------------------------------");
                            Write.flush();
                            Write.close();
                            loginForm lgf = new loginForm();
                            lgf.setVisible(true);
                            lgf.pack();
                            lgf.setLocationRelativeTo(null);
                            lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
          
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                    
                    }
                
            }catch(Exception e){
                 
            }
       }
         }
        }
    }//GEN-LAST:event_PhoneNumKeyPressed
/*this method UsernameKeyPressed() allow the user to complete the opration
    by pree the key enter on the keybord
    */
    private void UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
              String name = Name.getText();//get the full name from the JTextField
        String phonenum = PhoneNum.getText();//get the Phone number from the JTextField
        String username = Username.getText();//get the username from the JTextField
        String pass = Password.getText();//get the password from the JTextField
        /*check if  the field is  empty or not
       and the flag = true he/she gets an JOptionPane message error and reset the wendow
       */
         if(username.isEmpty() || pass.isEmpty()|| name.isEmpty()||phonenum.isEmpty()){
             JOptionPane.showMessageDialog(null, "Name/Phone number/"+"Username/Password "+
                     "should not be empty","Error",JOptionPane.ERROR_MESSAGE);
             flag = true;
              Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
        }else {
             /*if the fields are not empty 
             check if the username and the password are exist or not
             */
             if(flag == false){
        try{
                File file = new File("costumers.text");
                Scanner scan = new Scanner(file);
                while(scan.hasNext()){
                    String  line = scan.nextLine();  
                    if (line.equals(username)){
                            flaguser = true;            
                }
                      if (line.equals(pass)){
                            flagPass = true;            
                }
                    }
                /* if the username is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flaguser){
                        JOptionPane.showMessageDialog(null,"The username is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /* if the password is exist 
                show JOptionPane message error and reset the wendow
                */
                 if(flagPass){
                        JOptionPane.showMessageDialog(null,"The password is already exist");
                            Register rgf = new Register();
                            rgf.setVisible(true);
                            rgf.pack();
                            rgf.setLocationRelativeTo(null);
                            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                    }
                 /*if the username and the password are not exist
                 complete the regestration and go to the login wendow
                 */
                    if(!(flaguser && flagPass)){
                        try {
                            FileWriter F = new FileWriter("costumers.text",true);
                            PrintWriter Write = new PrintWriter(F);
                            Write.println(name +"\n"+ phonenum +"\n"+ username+"\n" + pass );
                            Write.println("----------------------------------------------------");
                            Write.flush();
                            Write.close();
                            loginForm lgf = new loginForm();
                            lgf.setVisible(true);
                            lgf.pack();
                            lgf.setLocationRelativeTo(null);
                            lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
          
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                    
                    }
                
            }catch(Exception e){
                 
            }
       }
         }
        }                   
                              
    }//GEN-LAST:event_UsernameKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField PhoneNum;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegester;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
